### ISSUE TITLE
Middlewares not working right

### ISSUE THREAD

**Issue by tsndr** [markusahlstrand/cloudworker-router#31]
I was just trying to use your router to migrate an API to cloudflare workers, while testing I noticed that the middleware system doesn't work right.

This will return 404 for no reason:
```javascript
const Router = require('cloudworker-router')
const router = new Router()

router.get('/test', async (ctx, next) => {
    next()
}, async ctx => {
    ctx.status = 204
})

addEventListener('fetch', event => {
    event.respondWith(router.resolve(event))
})
```

Maybe I'm just doing it wrong, but it's not really documented.

**Comment by markusahlstrand** [comment]
Hi @tsndr ,

It's not the working like middlewares in express but like in koa. At least you can't specify middlewares like that in koa... If I'm wrong we should definitely add support for it as well.

In this (untested..) example below the middleware would add a dummy header to all requests:

```
const Router = require('cloudworker-router')
const router = new Router()

router.use(async (ctx, next) => {
  ctx.set('foo', 'bar');
  await next(ctx);
});

router.get('/test', async (ctx, next) => {
    ctx.status = 200;
    ctx.body = 'Hello world';
})

addEventListener('fetch', event => {
    event.respondWith(router.resolve(event))
})
```

I started moving out middlewares from the cloudproxy to this repo so that they can be used directly with the router as well: https://github.com/markusahlstrand/cloudworker-middlewares
Maybe it explains better how it works? Let me know if it's still unclear and we could add some better info in the readme.

**Comment by tsndr** [comment]
Sorry, I'm not familiar with koa. In my API I need to define route specific middleware, which seems to not be possible in koa. So I guess I need to find another solution. Thank you for the explanation :)

**Comment by markusahlstrand** [comment]
Hi @tsndr , I don't think it should be a problem. You can just define it a separate route:
const Router = require('cloudworker-router')
const router = new Router()

```
router.get('test', async (ctx, next) => {
  ctx.set('foo', 'bar');
  await next(ctx);
});

router.get('/test', async (ctx, next) => {
    ctx.status = 200;
    ctx.body = 'Hello world';
})

addEventListener('fetch', event => {
    event.respondWith(router.resolve(event))
})
```

Or.. you just wrap the handler function directly.
